### ISSUE TITLE
Add request logging

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/server#19]
Output default request logs

**Comment by wilsonkasey** [comment]
I am willing to help here but I need guidance on exactly where this should be put.

**Comment by drimpact** [comment]
That is great news @wilsonkasey.

I have not looked in to it too much at the moment, but I imagine there will be logging middleware for the default go http handler available. As an example it looks like the gorilla library has a logging middleware for their router (not suggesting you use this, just as an example).

The http.handler is set up in https://github.com/impactasaurus/server/blob/master/cmd/main.go.
