### ISSUE TITLE
Service report: don't include meetings with no answers

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/server#23]
Currently the first and last meetings for a beneficiary are used in the JOC report, even if they have no answers. Only consider a meeting valid if it has > 0 answers.

**Comment by nikw92** [comment]
Interested in taking this issue.

**Comment by nikw92** [comment]
Might take some time since I'm unfamiliar with the server code but I'll deliver sooner or later.

**Comment by drimpact** [comment]
This has been overtaken by events. With the introduction of #57, this will not longer be an issue.
