### ISSUE TITLE
QuestionSet: Question Skipping Allowed

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/server#30]
Add a new boolean attribute to question sets: `skippable`. By default this should be `false`. It should be an optional argument when creating a question set.

Blocks impactasaurus/app#105.

**Comment by themakshter** [comment]
I will work on this

**Comment by themakshter** [comment]
Trying to confirm the requirement. We want to make a whole question set skippable? And this would determine if it's questions can be skipped? Or we are adding skippable to the question object? I am a bit confused by the wording.

**Comment by drimpact** [comment]
I think adding it to the question set would be best. This would mean that if true, all questions can be skipped within the question set.
