### ISSUE TITLE
Optional notes for assessment

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/server#32]
Assessments (aka meetings) should support an optional set of notes. These will capture any additional information gathered from the beneficiary whilst conducting the assessment which may have not related to any questions. It could also be used to record actions and goals.

Should expect the notes to be arbitrarily large.

**Comment by drimpact** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Assessment notes](https://trello.com/c/W0e2Xt9k/24-assessment-notes)

**Comment by themakshter** [comment]
This is basically a `notes` field for the whole meeting, right?

**Comment by drimpact** [comment]
yes that is right @themakshter. I think it is important for the people doing the assessments to be able to capture notes that they can review at the next assessment.

**Comment by drimpact** [comment]
@themakshter hope you dont mind me stealing this from you. Some of my frontend plans are reliant on this, so I would like to get it in.

**Comment by drimpact** [comment]
Closed by d43fd63d691d009286d6e7092c891bed0d6ae354
